services:
  php:
    image: php:8.3-fpm
    container_name: overcreate-php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./backend/.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: bash -lc "docker-php-ext-install pdo_mysql bcmath exif && php-fpm"

  nginx:
    image: nginx:1.25-alpine
    container_name: overcreate-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: overcreate-mysql
    environment:
      MYSQL_DATABASE: overcreate
      MYSQL_USER: overuser
      MYSQL_PASSWORD: overpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  dbdata: {}
